create table projects (
  id bigint generated by default as identity primary key,
  name text not null,
  target_hours integer not null default 0,
  created_at timestamptz default now() not null
);

comment on table projects is 'Stores project-specific allocation targets.';