create table public.pacing_alerts (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects
(id) on
delete cascade,
  user_id uuid
not null,
  alert_sent_at timestamptz not null default now
(),
  -- Ensure we only store one alert record per project per user
  constraint unique_project_user_alert unique
(project_id, user_id)
);

comment on table public.pacing_alerts is 'Tracks when a pacing alert has been sent for a specific project to avoid sending multiple alerts.';