create table settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value text not null,
  created_at timestamptz default now
() not null
);

comment on table settings is 'Stores application settings and secrets.';

-- Insert placeholder rows. The user will update these from the app.
-- We assume a single-user system, so we can hardcode the keys.
insert into settings
    (key, value)
values
    ('clockifyApiKey', ''),
    ('clockifyWorkspaceId', ''),
    ('clockifyUserId', '');