create table weekly_summaries (
  id bigint generated by default as identity primary key,
  project_id bigint references projects
(id) on
delete cascade not null,
  target_hours integer
not null,
  logged_hours real not null,
  week_ending_on date not null,
  created_at timestamptz default now
() not null,
  constraint unique_project_week unique
(project_id, week_ending_on)
);

comment on table weekly_summaries is 'Stores historical weekly summaries of project hours.';